<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_retreatgroup_deleteParticipant</name>
   <tag></tag>
   <elementGuidId>d8a81dc4-12ef-43ba-99ff-ef5786c9b149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//td[contains(text(),&quot;Participantlast-K&quot;)])[1]/following::i[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
