<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_editVolunteer_clearSecondaryRole</name>
   <tag></tag>
   <elementGuidId>c3b1486a-ef74-4ae2-a630-a6744f80b74b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ng-select[@id='volunteer-secondary-role-dropdown']//span//span[@class='ng-clear']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ng-select[@id='volunteer-secondary-role-dropdown']//span//span[@class='ng-clear']</value>
   </webElementProperties>
</WebElementEntity>
