<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_editVolunteer_experienceDropDown</name>
   <tag></tag>
   <elementGuidId>cd88883a-7515-4cd8-b7d9-e2c4458d7f1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='experience-dropdown']//div//span[@class='ng-value-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
