<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kendoDropdown_profiles_value</name>
   <tag></tag>
   <elementGuidId>2ec3c003-85d6-49e5-87df-8e9e7f33fc53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@class='k-item'][text()=&quot;${selectValue}&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@class='k-item'][text()=&quot;${selectValue}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
