<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropDownValue_fbWizardLightbox_leaders</name>
   <tag></tag>
   <elementGuidId>8c533442-8db3-4217-9db3-092532a3092b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@role='listbox']//mat-option//span[text()=&quot;${leaders}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@role='listbox']//mat-option//span[text()=&quot;${leaders}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
