<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropDownValue_fbWizardLightbox_participant</name>
   <tag></tag>
   <elementGuidId>24416291-13b3-4791-ad80-35bc02e831d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@role='listbox']//mat-option//span[text()=&quot;${participantRole}&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@role='listbox']//mat-option//span[text()=&quot;${participantRole}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
