<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_fbWizardLightbox_leaders</name>
   <tag></tag>
   <elementGuidId>619c9ae7-8c80-46af-8e05-513bfb4a08b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@class='mat-radio-outer-circle'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@class='mat-radio-outer-circle'])[4]</value>
   </webElementProperties>
</WebElementEntity>
