<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_fbWizardLightbox_participants</name>
   <tag></tag>
   <elementGuidId>0d61bce5-97ae-4015-91b1-ed87f0faa309</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@class='mat-radio-outer-circle'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@class='mat-radio-outer-circle'])[3]</value>
   </webElementProperties>
</WebElementEntity>
