<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_editProfile_clearSecondaryRole</name>
   <tag></tag>
   <elementGuidId>a33fe2a7-a2d8-440d-b2cd-ef06dad2e109</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ng-select[@id='volunteer-secondary-role-dropdown']//span//span[@class='ng-clear']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ng-select[@id='volunteer-secondary-role-dropdown']//span//span[@class='ng-clear']</value>
   </webElementProperties>
</WebElementEntity>
