<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropDownValue_sessionOverview_endTime</name>
   <tag></tag>
   <elementGuidId>46504318-bf6a-45f3-a4b4-dcbfe5f0b3d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-autocomplete-0']//mat-option/span[text()=&quot;$(endTime)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
