<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_registration_selectDate</name>
   <tag></tag>
   <elementGuidId>6f4e0ae2-d2e8-48c2-86bc-9071a0742b81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='ngb-dp-day']//div[text()=&quot;${sessionStartDate}&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='ngb-dp-day']//div[text()=&quot;${sessionStartDate}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
