<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropDownValue_fbWizardLightbox_secondaryRole</name>
   <tag></tag>
   <elementGuidId>c5ecb2bf-0c77-458d-9851-e9449d703edf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='volunteerSecondaryRole-panel']//mat-option//span[text()=&quot;${secondaryRole}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='volunteerSecondaryRole-panel']//mat-option//span[text()=&quot;${secondaryRole}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
