<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_retreatTile_retreatNameOntile</name>
   <tag></tag>
   <elementGuidId>84001844-4cca-4a19-9879-dd901a3e4ecb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='itemContainer']//label[@id='retreatName'][text()=&quot;${retreatName}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='itemContainer']//label[@id='retreatName'][text()=&quot;${retreatName}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
