<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_calendar_day</name>
   <tag></tag>
   <elementGuidId>8fd4da2c-8fc2-4b77-8b3b-9e896f933fca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kendoSchedulerPDFCommand']//following-sibling::ul//li//a[contains(text(),'Day')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
