<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_calendar_rightArrow</name>
   <tag></tag>
   <elementGuidId>76a3b376-9e6c-45fa-94d2-7687535e4be2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kendoSchedulerPDFCommand']//following-sibling::ul//li//a[@class='k-link']//span[contains(@class,'right')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
