<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_calendar_leftArrow</name>
   <tag></tag>
   <elementGuidId>aaa3f92b-c756-4ca6-a512-4ba15a1bd06b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kendoSchedulerPDFCommand']//following-sibling::ul//li//a[@class='k-link']//span[contains(@class,'left')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
