<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_scheduleMeeting_selectMonthYear</name>
   <tag></tag>
   <elementGuidId>6c6814c0-1cbb-4c15-8b7a-0b376ef40467</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//kendo-calendar//kendo-calendar-viewlist//kendo-calendar-header//span)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
