<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_sessionTile_sessionNameOnTile</name>
   <tag></tag>
   <elementGuidId>401a3533-b791-46d1-8a92-07cfc11ecd6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='itemContainer']//label[@id='sessionName'][text()=&quot;${sessionName}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='itemContainer']//label[@id='sessionName'][text()=&quot;${sessionName}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
