<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_editMeeting_selectMonthYear</name>
   <tag></tag>
   <elementGuidId>fdb06b24-c8c1-44d4-bc1b-ac4638a72053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//kendo-calendar//kendo-calendar-viewlist//kendo-calendar-header//span)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
