<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS 08-Session Overview Tile validation</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>77ae751b-f3ae-4ad8-bb62-a44778a43f5d</testSuiteGuid>
   <testCaseLink>
      <guid>2123b09a-8d02-4627-85b4-b5275ce456c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0994e49b-bb9a-4bc3-809d-132fa9cbb209</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/General Actions/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>0994e49b-bb9a-4bc3-809d-132fa9cbb209</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0994e49b-bb9a-4bc3-809d-132fa9cbb209</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0994e49b-bb9a-4bc3-809d-132fa9cbb209</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3cdce3b0-44fd-4783-8425-49b6fe376305</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Encounter Module/Session Actions/Session Actions-Session Overview/Session Overview - Validate Session details on tile and overview page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bd2e9ab-4fbe-42e5-89f3-f251f7f3f8ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7845bec-e4db-42ac-a3fb-d28c34216ada</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d023171-45df-4bd1-9006-a1d0a5ec457d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c504cf7a-fc23-4bdb-a7bc-1116cce886f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e740ef0-9f81-4c2a-bc28-714a6b23a919</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3e78ac0-340d-4278-bc05-f52aef1ed2dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea1d1547-44f2-44dc-8b63-9d080f3718cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>956619d9-eb98-4c3f-89d3-d63fa39c2268</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb0f6374-2b13-42b3-aa5b-e40acde10528</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>701bd995-4521-4c73-b029-0a0499eba4a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7ca11fc-972e-4b24-858f-6ee38c53cea7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d5eb934-31ff-4e37-89a3-0ed77f3028c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6d0e147-1c6f-4b52-b9c1-5a192941a205</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2aa0a2c-3c3c-4339-9702-6307395e396f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73abf3c3-3b6d-4363-ba59-a8b24621cbfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4d411b1-2b54-43e7-ad40-b4e45c09ff22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d41cd48-f1ec-4a34-88cd-128b0b677dde</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02ce88bb-3603-4014-b988-1f581ddd59f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66ae617f-bca8-4a9e-ae8c-506ba4bdf9c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8f2a55df-1e95-46d0-b906-512d719f3f1d</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>7</value>
         </iterationEntity>
         <testDataId>Data Files/General Actions/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>8f2a55df-1e95-46d0-b906-512d719f3f1d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8f2a55df-1e95-46d0-b906-512d719f3f1d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8f2a55df-1e95-46d0-b906-512d719f3f1d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f5b7859-95f8-472b-b4ee-830e2c233807</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Encounter Module/Session Actions/Session Actions-Session Overview/Participant Count on Session tile</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4c5ed4e2-e79c-4556-8104-0c16bf25f97e</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>3</value>
         </iterationEntity>
         <testDataId>Data Files/Sessions</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>4c5ed4e2-e79c-4556-8104-0c16bf25f97e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>SessName</value>
         <variableId>fdeeb236-7311-4ea8-83cc-254a745337ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c5b5347-cc62-495f-92f8-c7f7de10c061</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
