<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS 06-Session Food Actions</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>02f3c2b6-f310-4c91-a26c-7fcf10e3380b</testSuiteGuid>
   <testCaseLink>
      <guid>b0674bbf-4a3c-4ba7-871e-185f7159e6b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e00a5cec-9865-491c-a0af-4cb566c71aad</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>3</value>
         </iterationEntity>
         <testDataId>Data Files/Encounter/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>e00a5cec-9865-491c-a0af-4cb566c71aad</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e00a5cec-9865-491c-a0af-4cb566c71aad</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e00a5cec-9865-491c-a0af-4cb566c71aad</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8c6cb00-fd8d-40fb-89a4-17f22c248555</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Encounter Module/Session Actions/Session Actions- Food/Verify Number of Meetings and Input Food Notes to Save</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c9eb51e-73ba-4e68-bfa9-6806407bf3eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b11ade34-7913-4228-92a3-4bc3b76b04d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcc9a842-d7d7-4ca1-ba8d-7b17115e98b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b9845b5-16ae-4f10-99c3-a1bec2103016</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e57329b0-1f4e-4694-a6e2-53fd4df69576</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>8</value>
         </iterationEntity>
         <testDataId>Data Files/Encounter/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>e57329b0-1f4e-4694-a6e2-53fd4df69576</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e57329b0-1f4e-4694-a6e2-53fd4df69576</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e57329b0-1f4e-4694-a6e2-53fd4df69576</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd363e5f-53bd-4a15-b3f7-371ed74f02dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Encounter Module/Session Actions/Session Actions- Food/Validate Food Meeting Notes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b17911a3-92f4-48c1-8e77-bb18b57a2d31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfe517c8-e721-4692-a68b-639c7f5373d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e30c4bba-9da6-4d68-8057-05a646387e4a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b1efcfc-8d79-4d4b-99b6-f092acc69666</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3f1b3a76-7771-4a0a-899a-77adcf5a2ced</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>8</value>
         </iterationEntity>
         <testDataId>Data Files/Encounter/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>3f1b3a76-7771-4a0a-899a-77adcf5a2ced</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3f1b3a76-7771-4a0a-899a-77adcf5a2ced</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3f1b3a76-7771-4a0a-899a-77adcf5a2ced</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9357ffea-f5a2-4ebd-b834-40ee7ade27ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Encounter Module/Session Actions/Session Actions- Food/Add Session Food Budget and Validate</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af6f2b86-cd87-4c85-9204-114fdeab07ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ebd974d-efa4-476a-bcf2-ba08263ca334</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb30bb31-76a2-4c0c-81ef-e2cc277d3be7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6d37c074-25d4-4642-a77b-5df83bd394ee</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>8</value>
         </iterationEntity>
         <testDataId>Data Files/Encounter/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>6d37c074-25d4-4642-a77b-5df83bd394ee</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6d37c074-25d4-4642-a77b-5df83bd394ee</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6d37c074-25d4-4642-a77b-5df83bd394ee</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4fa25ff0-a5d2-413a-a865-6df8ed3bfdba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Encounter Module/Session Actions/Session Actions- Food/Create Food Responsibilities</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
