<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS 15 - Inform - Validate View Stats Table</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1d7a5dd8-326c-42bf-ab43-8828f261a6fb</testSuiteGuid>
   <testCaseLink>
      <guid>47ee27ce-bb07-4391-8670-2649d28dbb6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>932e864b-7993-4fb6-b088-106abcd19528</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>9</value>
         </iterationEntity>
         <testDataId>Data Files/General Actions/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>932e864b-7993-4fb6-b088-106abcd19528</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>932e864b-7993-4fb6-b088-106abcd19528</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>932e864b-7993-4fb6-b088-106abcd19528</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ab4cefbe-1fdf-4f5f-801e-bdd67b399715</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Encounter Module/Session Actions/Session Actions- Attendance/Click Attendance boxes for Participants and Volunteers</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d95d5f40-8c60-4c06-b64c-f109fada6212</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>6-7</value>
         </iterationEntity>
         <testDataId>Data Files/People</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d95d5f40-8c60-4c06-b64c-f109fada6212</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Attendance</value>
         <variableId>d7b8a7ef-158d-44d4-97bd-149c5cf68484</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d95d5f40-8c60-4c06-b64c-f109fada6212</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LastName</value>
         <variableId>ca0a276a-3f59-47d3-b712-a0a7ef10d9a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d95d5f40-8c60-4c06-b64c-f109fada6212</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FirstName</value>
         <variableId>262783bf-a95e-45dc-8565-82bd127f529a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d95d5f40-8c60-4c06-b64c-f109fada6212</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>participantOrVolunteer</value>
         <variableId>10e88bd3-cc3f-4005-a0b9-75066def8865</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6861ae9-8bfc-4a4f-934f-f04e91bc681f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>01be9a5d-661a-48a0-af85-66bca2b3e9ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Encounter Module/Session Actions/Session Actions- Attendance/Validate Attendance count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de55afce-a468-4348-850d-a002b479e7dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ea62197-05b4-4f10-a983-32cb244beef3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5729e90e-bd31-4b78-8279-4b6b189a6a00</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/General Actions/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>5729e90e-bd31-4b78-8279-4b6b189a6a00</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5729e90e-bd31-4b78-8279-4b6b189a6a00</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5729e90e-bd31-4b78-8279-4b6b189a6a00</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83f70ca1-91c1-404e-bd6f-8b491ec6a67c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Inform/Statistics/Statistics_View attendance percentage for all session</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>cc55ee3f-5943-4461-9766-33c099c157db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>94c5a996-4748-4b29-a3d3-837c2641cccd</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/General Actions/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>94c5a996-4748-4b29-a3d3-837c2641cccd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>94c5a996-4748-4b29-a3d3-837c2641cccd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>94c5a996-4748-4b29-a3d3-837c2641cccd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2c0c62b7-b454-460d-8b68-e4c1b01f9762</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Inform/Statistics/Statistics_Validate Status Table values</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0b14d83-7c15-413d-869e-fa646c3ebf5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a523c144-0a93-4e09-8113-ef0026f57193</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f13977f8-bc02-4b3e-ab5e-0e08c6be0a91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3e9e078-c9c7-48fa-9ea9-6260f66b9e12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d6c6b8f-3caa-4cf0-aca6-772d2a53091d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0443c1c-636f-4fb3-be30-6c48e1a8dce1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c5f043d-f9ab-457c-b5b6-606cce08265e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a685d79-9103-4b95-80c4-e3c4d813a803</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f4e11f4-3c6b-4ff0-a134-a15d395b8bcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3237f6a-62b9-4abe-8287-0290bd6b3d72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>baea0d71-ac33-42f9-8972-680973584aa3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19c26966-ff82-458d-b081-562035fc916c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb87ef6d-fdd0-405d-86eb-2585fff3484a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dc3afa9-8e9d-4da3-ba52-2973a35db564</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f58b4f4c-5b99-410e-a8fd-0b06585275ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80b785ff-f992-4ba9-8567-02b89e0a9ca8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d649eca2-6c27-4137-bab9-3a1eb5b901d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e44ec381-d3e4-4a94-8222-38d0d017d59c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1d0a5de-8140-4b3d-b746-ac82a794c80e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b01a2950-0c05-43b9-ab02-6961e8cfc700</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c03ff827-72c4-4236-b134-080b98bde503</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c4d3bbd-4298-41a7-83f1-944eeffd473d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84d20e0f-b5cd-461f-a7a2-2c2852aab7bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0a319b9-5e0f-4534-add9-4b40387abfda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73ca3afe-f9d1-4579-9ba3-a3ab776598a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9d75a58-5bb1-4207-90f7-93d8eee62225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c1fec21-583c-4dbb-976c-22d1086aef7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be09ffcd-2daf-4cea-a723-ffba48afe147</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56161c2d-6404-452e-807b-f79b43bb3ce3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d7209e2-a498-4ce0-a982-4f3a7c8bd83a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ab26cb3-9c6f-4ba3-8a7a-c8789d715176</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a666d835-ac90-4b72-9a27-e0f5b3625662</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdcaddd3-450b-4b2a-ae43-f2ddf5f87fa8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d77ce345-d241-4320-8d23-dac5a159c13a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee4c285b-8766-414c-8cf1-d83b0f88fec6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edd0ac73-8fef-4823-a85c-c7a1c0600969</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da88a137-b5c8-49a2-85d1-6d9d9133d7a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e12be32f-6a83-4ef5-b1e5-a53230e0fe3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71be18a8-adcc-4dc7-aab4-2c7fe9bbfc1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>034054c1-cb9c-4242-8d22-5d1f44f0fa66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bd38b1a-cdba-4b16-8c85-17e42c155595</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b74b72c-7626-4458-a308-ce0d41d1a5f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1aafa9af-d1aa-479e-aacf-5a54c10adb28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c866a9d1-1680-4283-a1de-b87d32e7ffe2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e596178b-ac1a-4072-8f81-cacffd2066cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a52d4b5-3571-42b3-888e-9e917de71f0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29c479ce-bf47-4c7d-a3ab-aafe1e39c817</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88833ee6-750c-412d-910a-873f6cbeb88e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a020da6-8bea-4659-86d9-335e2ccd2112</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7adb8642-7543-4dfd-b675-0951b114bedc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02d9647d-8c24-447b-8787-67cb4ba25e0f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>845693cd-77fd-4f9a-9579-3fd277b3e80f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>96535a34-3d5b-458c-b105-52c5b7922fa1</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/General Actions/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>96535a34-3d5b-458c-b105-52c5b7922fa1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>96535a34-3d5b-458c-b105-52c5b7922fa1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>96535a34-3d5b-458c-b105-52c5b7922fa1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef5dd415-3dd7-41ce-9ddb-e17df7bb89dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Inform/Statistics/Statistics_View Session Rating for all session types</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53194d3f-5738-4077-8a42-cde975ed3db7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dc91c9cf-97f8-49e0-9037-8b535f9eb552</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>33115197-a4d1-4619-b485-ab7d8be5ed3e</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/General Actions/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>33115197-a4d1-4619-b485-ab7d8be5ed3e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33115197-a4d1-4619-b485-ab7d8be5ed3e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33115197-a4d1-4619-b485-ab7d8be5ed3e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b233853-f798-43fc-9295-f4ed3b5c1002</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Inform/Statistics/Statistics_View Session Rating for specific session type</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4f45a62b-23fd-467a-b5aa-673dd0b82a8c</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/Sessions</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>4f45a62b-23fd-467a-b5aa-673dd0b82a8c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>SessType</value>
         <variableId>703585d6-c1ca-40a0-94a9-04bcf30b3586</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0363811a-8906-4941-86e6-935bce206a74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca7ef693-c8da-4e60-b9bf-6ce8ab533616</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e490692e-ca84-407b-9f0b-05ee0f5fe684</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/General Actions/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>e490692e-ca84-407b-9f0b-05ee0f5fe684</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e490692e-ca84-407b-9f0b-05ee0f5fe684</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e490692e-ca84-407b-9f0b-05ee0f5fe684</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b427cc7f-95e7-46ad-9b4b-6c87b8dd4bde</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Inform/Statistics/Statistics_Get Volunteer count for all Sessions</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1cfc159b-72c3-4bc6-9114-517ced7862a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b1799273-78e2-45f6-a807-84a0453381be</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>6</value>
         </iterationEntity>
         <testDataId>Data Files/General Actions/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>b1799273-78e2-45f6-a807-84a0453381be</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b1799273-78e2-45f6-a807-84a0453381be</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b1799273-78e2-45f6-a807-84a0453381be</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>294e407f-71e0-471d-bdf7-218b19d57096</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Inform/Statistics/Statistics_Validate Volunteer Conversion on Statistics</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aca51e2b-bb29-4d8d-94c0-a6a0179404b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe15e661-5a32-4584-b18f-15a938825be7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3e311a0a-2ee3-4a56-bda9-e7d38b84dcb5</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/General Actions/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>3e311a0a-2ee3-4a56-bda9-e7d38b84dcb5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3e311a0a-2ee3-4a56-bda9-e7d38b84dcb5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3e311a0a-2ee3-4a56-bda9-e7d38b84dcb5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d5e0962-0a82-40c0-8876-eab0f0cc982a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Encounter Module/Session Actions/Session Actions-Session Overview/Delete Session</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b41015b4-6e22-4c25-a53b-46bb4e697b94</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
