<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS 21 - Cmmunication - Session,Retreat and Grow</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>89a772b6-ce72-4eb5-87a6-9dae89fe2236</testSuiteGuid>
   <testCaseLink>
      <guid>f7cfbf37-c8d0-41b2-9753-139664f7358e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8d40d5bc-8f57-4a5a-b617-8c758e70e769</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>10</value>
         </iterationEntity>
         <testDataId>Data Files/General Actions/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>8d40d5bc-8f57-4a5a-b617-8c758e70e769</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8d40d5bc-8f57-4a5a-b617-8c758e70e769</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8d40d5bc-8f57-4a5a-b617-8c758e70e769</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>35821bd8-a913-4094-9a91-67b0be4de492</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Encounter Module/Encounter(Session or Retreat)/Retreat/Retreat Participants/Communication-Email Retreat Participants</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f0fe1b1-6cca-4193-9218-8c6d54a009ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00876255-c1eb-407b-a4ca-6c9365501f78</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d8cafd1-3496-4c28-98c1-b63098d87787</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Encounter Module/Encounter(Session or Retreat)/Retreat/Retreat Participants/Communication-Text Retreat Participants</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cfbfaf1-5a88-4344-8d17-cc0f958480f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0f48daf-483a-4aac-a258-de9a0d87897c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d458d75-c713-4202-a531-08b8bfabe48a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e1049824-4d7f-4655-bfca-d08f77f2508b</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>11</value>
         </iterationEntity>
         <testDataId>Data Files/General Actions/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>e1049824-4d7f-4655-bfca-d08f77f2508b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e1049824-4d7f-4655-bfca-d08f77f2508b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e1049824-4d7f-4655-bfca-d08f77f2508b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b505b61-dcc7-4c7d-aef6-25a742df58f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Encounter Module/Encounter(Session or Retreat)/Retreat/Retreat Volunteers/Communication-Email Retreat Volunteers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9735f407-7ca7-4213-a8ea-73b76cbb4dfd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20899965-9081-4562-bd49-8b7eaf36b691</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c77f3ef5-85aa-45e8-a24f-05e3e7bea503</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Encounter Module/Encounter(Session or Retreat)/Retreat/Retreat Volunteers/Communication-Text Retreat Volunteers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e241598b-1998-4aca-95f5-30506261f0a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5ffc9e5-13d2-44aa-a933-92504dc2db74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f14d158-9020-48c6-b03f-7c58ec28773c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8384876f-490d-489b-88be-a662a5d46c66</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/General Actions/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>8384876f-490d-489b-88be-a662a5d46c66</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8384876f-490d-489b-88be-a662a5d46c66</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8384876f-490d-489b-88be-a662a5d46c66</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0cbc12a5-975c-4999-a056-c55fbaff01db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Profiles/Communication-Email Person on People page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>177a131e-404b-45d9-91ba-97f23f977683</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c04310ee-60f2-4954-98ef-30cb26d76761</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9dc4a17e-d29e-4d0a-856a-8a3213acb507</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Profiles/Communication-Text Person on People page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0da7823-d41e-4d2b-a752-42eda39d5cda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53648b83-ae2a-4feb-a69e-506874e72b3c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>112209f3-a0bf-4a01-ba47-092e132ac2bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cc2d11a7-9914-4957-b47c-86e1c05e7e55</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>27</value>
         </iterationEntity>
         <testDataId>Data Files/General Actions/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3100aee6-9abc-428f-a05f-2ad9b697f098</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Grow Module/Group/TC 07-Select Grow Group on Group Page</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>32ed8e81-a102-41a9-83a4-82846a830ffc</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/Grow-Groups</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>32ed8e81-a102-41a9-83a4-82846a830ffc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>GroupName</value>
         <variableId>cbfdd678-3baf-4421-9d63-f9938b593b57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79922e8d-441a-40a3-aa63-300475e2b0ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab2dca4e-9a27-4e56-af11-03dc7ab930db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ed5045a-622a-4ba3-91bd-834c54f7febf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7eb62015-ce88-42fb-97e1-df35f3f8f7b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Grow Module/Members/Communication-Email Grow Members</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49b233b9-cb1a-446d-aff0-fff4c370eda9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2c84b3f6-1c59-4f33-aa70-b86f0d0f201f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Grow Module/Members/Communication-Text Grow Members</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e988b51f-7752-4860-9a74-f76f456be839</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e52e870-68a4-402c-94eb-d5c97353dbfc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0e86d19-d6ea-4a76-b6f0-32a0bc057a52</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Actions/Common Actions- Module navigation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a2cf5189-cfd3-4e5b-87c6-ed6551f42fa4</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>31</value>
         </iterationEntity>
         <testDataId>Data Files/General Actions/moduleNavigation</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>a2cf5189-cfd3-4e5b-87c6-ed6551f42fa4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sidebarLink</value>
         <variableId>b61c0b35-bff5-4c32-ada8-cf8b3be74ae0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a2cf5189-cfd3-4e5b-87c6-ed6551f42fa4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sessionOrRetreatName</value>
         <variableId>de000f67-9f40-4c7f-a48f-ae318345ad75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfcbafbd-3913-4144-b552-1615dcae13f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c77c8356-9be4-4ab0-9de5-07f7dbf8dbb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5061e7-b768-4d66-a25e-ac7d1af1f332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94058d22-d974-4122-8d5a-4e89481ebb4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a2cf5189-cfd3-4e5b-87c6-ed6551f42fa4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>module</value>
         <variableId>a5cfb6f5-0a5d-4893-b309-dbfd563028df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2509f8a1-08d1-4c5d-8564-871f245b0041</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83f91b49-96ea-4628-b6c8-96c89f19b255</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Grow Module/People/Communication-Email Grow Members on Grow People page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c11668e-c228-47ce-ad62-e86e21845e9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6055229-e686-47fe-a168-15488c54faa1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>888d2b9c-beb8-4ace-9060-47d5a2619ac9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Grow Module/People/Communication-Text Grow Members on Grow People page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>450a46fe-f435-4faa-bd6f-86e38267a236</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
