<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_asignAccess_growAccessReadWriteCreate</name>
   <tag></tag>
   <elementGuidId>268c780e-b9f2-4801-b20a-65eda8aaa081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='grow_access']//ng-dropdown-panel//div//span[text()='Read/Write/Create']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
