<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_asignAccess_encounterAccessReadWrite</name>
   <tag></tag>
   <elementGuidId>28948e38-f785-4f85-a592-6c88fe5b2897</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='encounter_access']//ng-dropdown-panel//div//span[text()='Read/Write']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
