<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_fbDesignerVolunteer_gender</name>
   <tag></tag>
   <elementGuidId>03acf7fc-d951-420c-b8fa-664cead3c84d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='demographic-data-container']//table//tr//td[text()='Gender']//parent::tr//mat-slide-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
