<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_retreatdietaryrestrictionsRequired</name>
   <tag></tag>
   <elementGuidId>6626bed4-7124-47a8-8732-e425b0b3505a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='dietaryRestrictionsRequired']//ancestor::td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='dietaryRestrictionsRequired']//ancestor::td</value>
   </webElementProperties>
</WebElementEntity>
