<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_retreatchildcareRequired</name>
   <tag></tag>
   <elementGuidId>e634e244-d803-4b51-858d-ddbbd2bc713f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='childCareRequired']//ancestor::td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='childCareRequired']//ancestor::td</value>
   </webElementProperties>
</WebElementEntity>
