<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_childcarerequestDisplay</name>
   <tag></tag>
   <elementGuidId>3d31f39f-8a8b-47f3-aee7-261ad40bd9e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='childCareDisplay']//ancestor::td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='childCareDisplay']//ancestor::td</value>
   </webElementProperties>
</WebElementEntity>
